services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUN_ENV=production
      - APP_DATABASE_URL=postgres://postgres:postgres@db:5432/auctions
      - APP_SERVER_HOST=0.0.0.0
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auctions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
